# ----------------------------------------------------------------------------------------------------------------------
# vhdl_ls.toml
# ----------------------------------------------------------------------------------------------------------------------
# This file is used to configure the VHDL Language Server (vhdl_ls).
# It specifies the libraries and files to be included in the VHDL project.
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# Vunit: https://github.com/VUnit/vunit
# ----------------------------------------------------------------------------------------------------------------------

[libraries.vunit_lib]

files = [
    # I know this is a lot of files, but it is easiest way to include all files without hundreds of errors or
    # warnings
    ".venv/lib/python3.12/site-packages/vunit/vhdl/check/src/check_api-2008p.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/queue_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/codec_builder-2008p.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/event_common_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/integer_array_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/event_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/check/src/check_api.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/codec-2008p.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/string_ops/src/string_ops.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/codec_builder.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/api/external_string_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/id_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/data_types_context.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/logger_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/dictionary/src/dictionary.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/run/src/runner_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/path/src/path.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/event_private_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/run/src/run_api.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/dict_pkg-body.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/core/src/core_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/vunit_context.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/check/src/check-2008p.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/logger_pkg-body.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/ansi_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/queue_pool_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/log_levels_pkg-body.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/types.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/location_pkg-body-2008m.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/log_levels_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/common_log_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/codec.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/location_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/check/src/checker_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/check/src/checker_pkg-body.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/check/src/check.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/print_pkg-body.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/vunit_run_context.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/run/src/run_types.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/run/src/run.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/common_log_pkg-body.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/log_handler_pkg-body.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/print_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/core/src/stop_body_2008p.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/file_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/data_types_private_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/dict_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/core/src/stop_pkg.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/data_types/src/queue_pkg-body.vhd",
    ".venv/lib/python3.12/site-packages/vunit/vhdl/logging/src/log_handler_pkg.vhd",
]
is_third_party = true

# ----------------------------------------------------------------------------------------------------------------------
# Custom libraries
# ----------------------------------------------------------------------------------------------------------------------

[libraries.lib_rtl]
files = ["sources/**/*.vhd"]

[libraries.lib_bench]
files = ["bench/**/*.vhd"]
